export const TIMEOUTS = {
  SKELETON_LOADING: 1500,
  DEPLOYMENT_LOADING: 2000,
  FIX_SIMULATION: 3000,
};

export const LIMITS = {
  MAX_PROJECTS: 100,
  MAX_SEARCH_LENGTH: 100,
  CHUNK_SIZE_WARNING: 1000,
};

export const SCORES = {
  BASE: 100,
  SPEED_BONUS_THRESHOLD: 5,
  SPEED_BONUS: 10,
  COMMITS_THRESHOLD: 20,
  EFFICIENCY_PENALTY_PER_COMMIT: -2,
  QUALITY_BONUS_PER_FIX: 2,
  QUALITY_PENALTY_PER_FAILURE: -5,
  MIN_SCORE: 0,
  MAX_SCORE: 100,
};

export const STORAGE_KEYS = {
  UI_STATE: 'vajraopz-ui-storage',
  AUTH_STATE: 'vajraopz-auth-storage',
};
